requires 'AnyEvent';
suggests 'DBIx::Class::Core';
requires 'DBIx::Class::Schema';
requires 'File::Find::Object';
requires 'LWP::UserAgent';
requires 'Log::Any';
requires 'Log::Any::Adapter';
requires 'Module::Load';
requires 'Mongoose';
requires 'Mongoose::Class';
requires 'Mongoose::Document';
requires 'Moo';
requires 'Moose';
requires 'Moose::Role';
requires 'MooseX::Object::Pluggable';
requires 'MooseX::Singleton';
requires 'Net::SSH::Any';
requires 'Proc::Daemon';
requires 'Search::GIN::Extract';
requires 'Search::GIN::Keys::Deep';
requires 'Search::GIN::Query::Class';
requires 'Search::GIN::Query::Manual';
requires 'Term::ANSIColor';
requires 'Time::HiRes';
requires 'Time::Piece';
requires 'Try::Tiny';
requires 'URI';
requires 'Unix::PID';
requires 'YAML::Tiny';
requires 'namespace::autoclean';

on test => sub {
    requires 'Test::Simple';
};
