---
host: localhost
port: 23456
type: master
username: root
password: test

---
host: localhost
port: 23456
type: agent
username: root
password: test

---
host: localhost
port: 23456
type: node
username: root
password: test

#BootStrap configuration file