---
host: 127.0.0.1
port: 23456
type: node
username: root
password: test
#HW: "0,0" #alsa hw address for recording

---
host: localhost
port: 23459
type: master
username: root
password: test
#HW: "0,0" #alsa hw address for recording


##XXX: YAML is for prototyping now, we should get over it with autodetection probing the master
#---
#host: x.x.x.x
#port: 23457
#type: node
#description: "ih0"
#username: root
#password: password
#deployer: 'IH::Deployer::Debian' #If it's debian, i'll use a debian deployer :)


#BootStrap configuration file

