---
host: 127.0.0.1 ## here goes the real ip exposed to the trusted network
port: 23456
type: node #This indicate that i'm the node
username: root
password: test
#HW: "0,0" #alsa hw address for recording

---
host: localhost ## here goes the real ip address of the master node
port: 23459
type: master #this is the master
username: root
password: test
#HW: "0,0" #alsa hw address for recording


##XXX: YAML is for prototyping now, we should get over it with autodetection probing the master
