---
host: 192.168.1.129
port: 23456
type: master
username: root
password: test

---
host: localhost
port: 23459
type: node
username: root
password: test

---
host: 192.168.1.129
port: 23457
type: node
description: "ih0"
username: root
password: password
deployer: 'IH::Deployer::Debian' #If it's debian, i'll use a debian deployer :)


#BootStrap configuration file

