---
host: localhost
port: 23456
type: master
username: root
password: test

---
host: localhost
port: 23456
type: agent
username: root
password: test

---
host: 10.10.10.10
port: 23456
type: node
description: "ih0"
username: root
password: password
deployer: 'IH::Deployer::Debian' #If it's debian, i'll use a debian deployer :)


#BootStrap configuration file

